default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: vlad

development:
  <<: *default
  database: ruby_clone_dev

test:
  <<: *default
  database: ruby_clone_test

production:
  <<: *default
  database: ruby_clone_prod
